import type { Metadata } from "next";

import { AsidebarProvider } from "../context/context-openAsidebar";

import Aside  from "../components/layout/Aside";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-surface-app antialiased`}
      >
        <div className="flex min-h-screen items-center justify-center font-sans">
          <AsidebarProvider>
            <Aside
            className="relative w-70 h-screen bg-surface-sidebar" />

            <div className="flex-1 flex flex-col h-screen bg-surface-app">
              {children}
            </div>
          </AsidebarProvider>
        </div>
      </body>
    </html>
  );
}
